apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ocp-node01-bridges
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-node01"
  desiredState:
    interfaces:
      - name: br250
        description: Linux bridge between bond1.250 and br250
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.250.206
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.250
      - name: br251
        description: Linux bridge between bond1.251 and br251
        type: linux-bridge
        state: up
        ipv4:
          address:
            - ip: 10.216.251.181
              prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.251
      - name: br252
        description: Linux bridge between bond1.252 and br252
        type: linux-bridge
        state: up
        ipv4:
          address:
            - ip: 10.216.252.181
              prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.252
      - name: br139
        description: Linux bridge between bond1.139 and br139
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 192.168.139.240
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.139
      - name: br204
        description: Linux bridge between bond1.204 and br204
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.204.15
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.204