apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-gw2
  name: vm-gw2
spec:
  dataVolumeTemplates:
  - metadata:
      name: gw2-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 160Gi
        storageClassName: hostpath-provisioner
      source:
        http:
          url: "http://10.216.250.210:8008/PxPS-3604.qcow2"
          secretRef: ""
          certConfigMap: ""
    status: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-gw2
    spec:
      nodeSelector:
        kubernetes.io/hostname: "ocp-node03"
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk101
        machine:
        resources:
          requests:
            memory: 16Gi
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: gw2-dv
        name: datavolumedisk101
status: {}

