apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: master-0
  namespace: openshift-machine-api
  cluster-name: raven2
hosts:
  - hostname: node01
# Not sure if we need this section
#    labels:    
#      - name: eno1
#        macAddress: 78:ac:44:0c:aa:a0
#      - name: eno2
#        macAddress: 78:ac:44:0c:aa:a1
#      - name: eno3
#        macAddress: 78:ac:44:0c:aa:a2
#      - name: en04
#        macAddress: 78:ac:44:0c:aa:a3
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        mac-address: 78:ac:44:0c:aa:a0
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          #address:
          #  - ip: 192.168.105.20
          #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno1
          - eno2
        #mtu: 1500
      - name: bond0.205
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.205.226
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond0
          id: 205
      - name: bond1
        type: bond
        state: up
        mac-address: 78:ac:44:0c:aa:a2
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          # address:
          #  - ip: 192.168.151.20
           #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno3
          - eno4
        mtu: 9000 
      - name: bond1.250
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.250.206
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 150
      - name: br-250
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.250
      - name: bond1.251
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.251.181
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 251
      - name: br-251
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.251
      - name: bond1.252
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.252.181
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 252
      - name: br-252
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.252
      # - name: bond1.101
        # type: vlan
        # state: up
        # ipv4:
          # enabled: true
          # address:
          # - ip: 192.168.101.20
            # prefix-length: 24
          # dhcp: false
        # vlan:
          # base-iface: bond1
          # id: 101
      # - name: br-101
        # type: linux-bridge
        # state: up
        # bridge:
          # port:
          # - name: bond1.101
      - name: bond1.204
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.204.15
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 204
      - name: br-104
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.204     
    dns-resolver:
      config:
        server:
          - 10.216.105.111
          - 10.209.24.254
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.216.205.1
          next-hop-interface: bond0.205
          table-id: 254
  interfaces:  
    - name: "bond0"
      macAddress: 78:ac:44:0c:aa:a0
    - name: "bond1"
      macAddress: 78:ac:44:0c:aa:a2
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: master-1
  namespace: openshift-machine-api
  cluster-name: raven2
hosts:
  - hostname: node02
# Not sure if we need this section
#    labels:    
#      - name: eno1
#        macAddress: e4:43:4b:73:1f:e0
#      - name: eno2
#        macAddress: e4:43:4b:73:1f:e1
#      - name: eno3
#        macAddress: e4:43:4b:73:1f:e2
#      - name: en04
#        macAddress: e4:43:4b:73:1f:e3
spec:
  config:
    interfaces:
      - name: bond0
        type: bond-vlan
        state: up
        mac-address: e4:43:4b:73:1f:e0
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          #address:
          #  - ip: 192.168.105.20
          #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno1
          - eno2
        #mtu: 1500
      - name: bond0.205
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.205.227
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond0
          id: 205
      - name: bond1
        type: bond-vlan
        state: up
        mac-address: e4:43:4b:73:1f:e2
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          # address:
          #  - ip: 192.168.151.20
           #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno3
          - eno4
        mtu: 9000 
      - name: bond1.250
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.250.207
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 150
      - name: br-250
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.250
      - name: bond1.251
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.251.182
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 251
      - name: br-251
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.251
      - name: bond1.252
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.252.182
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 252
      - name: br-252
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.252
      # - name: bond1.101
        # type: vlan
        # state: up
        # ipv4:
          # enabled: true
          # address:
          # - ip: 192.168.101.20
            # prefix-length: 24
          # dhcp: false
        # vlan:
          # base-iface: bond1
          # id: 101
      # - name: br-101
        # type: linux-bridge
        # state: up
        # bridge:
          # port:
          # - name: bond1.101
      - name: bond1.204
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.204.15
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 204
      - name: br-104
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.204     
    dns-resolver:
      config:
        server:
          - 10.216.105.111
          - 10.209.24.254
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.216.205.1
          next-hop-interface: bond0.205
          table-id: 254
  interfaces:  
    - name: "bond0"
      macAddress: e4:43:4b:73:1f:e0
    - name: "bond1"
      macAddress: e4:43:4b:73:1f:e2
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: master-2
  namespace: openshift-machine-api
  cluster-name: raven2
hosts:
  - hostname: node03
# Not sure if we need this section
#    labels:    
#      - name: eno1
#        macAddress: e4:43:4b:73:22:30
#      - name: eno2
#        macAddress: e4:43:4b:73:22:31
#      - name: eno3
#        macAddress: e4:43:4b:73:22:32
#      - name: en04
#        macAddress: e4:43:4b:73:22:33
spec:
  config:
    interfaces:
      - name: bond0
        type: bond-vlan
        state: up
        mac-address: e4:43:4b:73:22:30
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          #address:
          #  - ip: 192.168.105.20
          #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno1
          - eno2
        #mtu: 1500
      - name: bond0.205
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.205.228
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond0
          id: 205
      - name: bond1
        type: bond-vlan
        state: up
        mac-address: e4:43:4b:73:1f:e2
        ipv4:
        #If access port no need for VLAN tag - if trunk port with vlans you need to configure bond and vlans correctly
        #enabled: false         
          enabled: true
          # address:
          #  - ip: 192.168.151.20
           #   prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: 802.3ad
          #options:
          #  miimon: '140' 
          slaves: 
          - eno3
          - eno4
        mtu: 9000 
      - name: bond1.250
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.250.208
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 150
      - name: br-250
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.250
      - name: bond1.251
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.251.183
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 251
      - name: br-251
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.251
      - name: bond1.252
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.252.183
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 252
      - name: br-252
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.252
      # - name: bond1.101
        # type: vlan
        # state: up
        # ipv4:
          # enabled: true
          # address:
          # - ip: 192.168.101.20
            # prefix-length: 24
          # dhcp: false
        # vlan:
          # base-iface: bond1
          # id: 101
      # - name: br-101
        # type: linux-bridge
        # state: up
        # bridge:
          # port:
          # - name: bond1.101
      - name: bond1.204
        type: vlan
        state: up
        ipv4:
          enabled: true
          address:
          - ip: 10.216.204.17
            prefix-length: 24
          dhcp: false
        vlan:
          base-iface: bond1
          id: 204
      - name: br-104
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond1.204     
    dns-resolver:
      config:
        server:
          - 10.216.105.111
          - 10.209.24.254
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.216.205.1
          next-hop-interface: bond0.205
          table-id: 254
  interfaces:  
    - name: "bond0"
      macAddress: e4:43:4b:73:22:30
    - name: "bond1"
      macAddress: e4:43:4b:73:22:32
---