apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ocp-node03-bridges
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-node03"
  desiredState:
    interfaces:
      - name: br250
        description: Linux bridge between bond1.250 and br250
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.250.206
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.250
      - name: br251
        description: Linux bridge between bond1.251 and br251
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.251.183
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.251
      - name: br252
        description: Linux bridge between bond1.252 and br252
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.252.183
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.252