apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cl1
  name: vm-cl1
spec:
  dataVolumeTemplates:
    - metadata:
        name: cl1-dv
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: hostpath-provisioner
        source:
          http:
            url: "http://10.216.250.210:8008/clc-7.1-3.6.1.3.qcow2"
            secretRef: ""
            certConfigMap: ""
      status: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cl1
    spec:
      nodeSelector:
        kubernetes.io/hostname: "ocp-node02"
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: datavolumedisk101
        machine:
        resources:
          requests:
            memory: 8Gi
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: cl1-dv
          name: datavolumedisk101
status: {}