apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ocp-node1-pxbridges
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-node1"
  desiredState:
    interfaces:
      - name: br250
        description: Linux bridge with bond1.250 as a port
        type: linux-bridge
        state: up
        ipv4:
          address:
          - ip: 10.216.250.180
            prefix-length: 24
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond1.250

