apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ocp-node1-bond1-configuration
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-node1"
  desiredState:
    interfaces:
    - name: bond1
      description: Bond with ports ens2f0 and ens2f1
      type: bond
      state: up
      ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '100'
        port:
        - ens2f0
        - ens2f1
      mtu: 1500

